### PR TITLE
added files for continuous integration (automatic testing)

### PR DESCRIPTION
**Pull request by jeffreyhanson**
I've submitted pull request with the travis and appveyor files. You just need to tell Travis and AppVeyor to use them. It's pretty painles - or if you add me to the repo I can set it up.

### CODE REVIEW

**Comment by ivanhanigan** [comment]
Thanks for the offer @paleo13 I have added you to the repo team.  Cheers.

**Comment by jeffreyhanson** [comment]
I've set up AppVeyor (for windows testing). Apparently, I need admin rights to set up Travis CI for ubuntu and mac OSX. Or if you would prefer, you could visit this page (https://travis-ci.org/profile/swish-climate-impact-assessment) and toggle the on button.

**Comment by ivanhanigan** [comment]
Thanks!
I flipped that switch and then pushed a modification to the DESCRIPTION
file to bump the version.
Does that do the trick?
Thanks so much for helping (your alias is now in the description cheers)

**Comment by jeffreyhanson** [comment]
Yeah, it's all set up now. If you click on the Travis and AppVeyor badges in the README, they take you to the respective pages with print outs of the logs of compiling the package and checking CRAN tests on it. 

Eg. if you click on 'Linux and Mac' badge/image, it takes you to the Travis CI website. Here it shows you the status of the package. You can view the logs for ubuntu by clicking on the build job with the penguin, and mac by click on the one with the apple. If you scroll through to the end of the log text, you can see why the build is failing (click the r-check grey box first to maximise the output), here the following code (in awaptools-Ex.R) is causing it fail:

> fileslist <- dir(pattern="grid$")
> r <- raster(fileslist[1])
> Error in .rasterObjectFromFile(x, band = band, objecttype = "RasterLayer",  : 
>   Cannot create RasterLayer object from this file; perhaps you need to install rgdal first

Also, my name's Jeffrey O. Hanson, so if you include that in the DESCRIPTION that would be great.

**Comment by ivanhanigan** [comment]
thanks jeff, I deleted some example code from get_awap_data.
hopefully it will succeed.
Cheers for the help getting that set up!

**Comment by jeffreyhanson** [comment]
No worries

Also, just in case you're not aware, if you set your working directory as the package directory on your computer, you can use devtools::test() to run all your unit tests automatically, devtools::run_examples() to run all the examples in the help files, and devtools::check() to run it through CRAN tests.

I find this quicker than waiting for Travis or AppVeyor to do the tests since they take 10+ minutes to just initialize.

**Comment by ivanhanigan** [comment]
Thanks! I usually use rstudio's build Panel and run CHECK. .. but it didn't
warn me about that failing example code. I'll try as you suggest.  Thanks
for the help

**Pull request merged**
